
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
